### PR TITLE
v2

### PR DESCRIPTION
**Pull request by natecavanaugh**
This is a pull request to track progress on the next version.
Here's generally what I'm hoping to get done:
- [x] Update ESLint and other dependencies to support ES6/7
- [x] Add support for linting React code
- [x] Allow projects/people to define their own config [1]
- [x] Use PostCSS to parse (S)CSS files and run rules against the AST rather than REGEX statements run on each line

Nice to haves:
- [ ] One I've wanted for a while was a visual difference between outright errors and warnings.

[1] There is a little bit of danger here with allowing people to define their own config, in that they could have certain rules turned off that they shouldn't (whether locally, or globally), and having their PR fail because it has errors that should have been spotted.
I have a few ideas for handling this. One idea would be to still show the error, but mask it in someway (whether greyed out, or some other mechanism) so that it doesn't appear directly as an error but that you still know your local config is not catching certain issues.
If I go with this one, it would be possible to hide those errors (in case there's just too much noise), but it would have to explicitly be done with a long format parameter of some kind.

The other option would be to just print a line after each file with something like:

```
4 errors and 5 warnings were ignored by local configuration.
```

or at the very bottom of the report:

```
10 errors and 12 warnings across 3 files were ignored by the local configuration.
Run the program with --no-config-rules in order to view the errors inline
```

Some of that still needs to be thought through a bit more though.

### CODE REVIEW

**Comment by mthadley** [comment]
This looks great so far, thanks for the work on this @natecavanaugh!

Regarding the feature of allowing a local config, what is an example use case for this? Would it be more for allowing projects to have a superset of the rules the CSF provides out of the box? The only use case I can imagine for ignoring errors is when a project starts using language features that CSF handle (like the issue we have in Loop currently with ES6).

**Comment by natecavanaugh** [comment]
Thanks @mthadley :) And sorry it's taken me so long to respond (I just randomly opened this page and saw your comment today... right now I have 76 unread github notifications, so I've been slow to get through them).

About your question, the primary example use case is exactly yours on the Loop teams, but also to help cover issues in other projects.

For instance, some projects have globals that they need to register. For instance, the Loop team has jest, LoopConstants, and LoopAssets, but other projects also have other ones that make it a pain to have to do a comment at the top of each file with `/* global Highcharts */` or whatever.

I could even see cases where in some projects, some rules need to be "silenced", since they may not be something we want to address (for instance, in the EE branches, some old patterns we have to live with because changing them would be too risky).

Those would be the main ones I can think of. Let me know if you have any thoughts on this.

Thanks again Mike :)

**Comment by mthadley** [comment]
@natecavanaugh That makes sense, and is definitely something we would find useful!

**Comment by jbalsas** [comment]
Hey @natecavanaugh, one thing about this... I think some of our old syntax rules may not be desirable for ES2015. For example, `Args should each be on their own line (args on start line)` won't allow us to do:

```javascript
doSomethingPromisable()
    .then((foo) => doSomethingMorePromisable(foo))
    .then((bar) => finish(bar)
```

Not sure if this is something we'd like to consider...

**Comment by natecavanaugh** [comment]
@jbalsas The rules are actually already handling this case. I added a test case to make sure we maintain it, but using single line arrow functions is allowed by the rules.

If you find a use case where it reports an error, can you file an issue? (or you can paste it here... either way :))
Thanks Chema!

**Pull request merged**
